### ISSUE TITLE
cts functionality and minicts dependency

### ISSUE THREAD

**Issue by edsu** [LibraryOfCongress/chronam#10]
Users of Chronicling America outside of the Library of Congress have no need for Content Transfer Services (CTS) related functionality. They also won't be able to install the minicts module since it is currently in LC's private git repository. At the very least minicts should be removed from the requirements.txt, and perhaps the tasks and management commands related to CTS should be moved from chronam.core into chronam.loc.

**Comment by johnscancella** [comment]
OBE, this is now in a separate requirements.pip file
