### ISSUE TITLE
chronam_sync fails  with Place matching query does not exist error

### ISSUE THREAD

**Issue by davidhart0** [LibraryOfCongress/chronam#100]
django-admin.py syncdb runs without a hitch updating tables in the database but when I run the next command django-admin.py chronam_sync it fails on RHEL 6.4 with the matching query error and on my Ubuntu 12.04 test box fails on the same command with [Errno 111] Connection refused.  I am following the github instructions but using solr-4.9.0 instead of the 4.4.0 version and have used alternatives to switch to jdk-7 which produces better results with the solr version.  Ubuntu uses python 2.7 so I was trying to see if that would make a difference.

**Comment by matthew-edwards** [comment]
I had the same problem. The default Solr port after installation was 8080. The settings.py had 8983. I updated the settings.py value and the chronam_sync command worked.

**Comment by davidhart0** [comment]
Wow thank you good work!
