### ISSUE TITLE
Re-searching with Advanced Search does not retain date criteria

### ISSUE THREAD

**Issue by nwy** [LibraryOfCongress/chronam#104]
When doing a search in advanced search for second time (or more), the years in drop downs revert back to defaults and do not retain the previously selected criteria.

Related to: #96

**Comment by myusuf** [comment]
@nwy, would you be able to provide some url examples of this issue? I fixed #96 and want to check if they are actually related.

**Comment by nwy** [comment]
Here's an advanced search result set for keyword "fire" and dates chose to be 1910-1920:

http://chroniclingamerica.loc.gov/search/pages/results/?dateFilterType=yearRange&date1=1910&date2=1920&language=&ortext=fire&andtext=&phrasetext=&proxtext=&proxdistance=5&rows=20&searchType=advanced

Clicking on Advanced tab after results come up will show that the date criteria has reset to 1836 and 1922.
