### ISSUE TITLE
Broken LOC theme / confusing themes

### ISSUE THREAD

**Issue by jechols** [LibraryOfCongress/chronam#107]
I was pulling the latest chronam down to try and see where our project's changes might make sense to push back up, but I'm not really sure what's going on with the built-in themes, so I'm not sure how to contribute any updates that include HTML changes.

The "loc" theme wasn't working at all, it kept giving me errors about missing lc/ files.  I'm not sure if there's a typo in this repo or if there's an "lc" directory that isn't part of the repo, but I wasn't able to stand up that theme at all.

Then I tried either core or example (sorry, I can't recall which as I kept tinkering with the site in lots of ways hoping to get things up and running, and had to scrap the VM to continue work on our Oregon Newspaper project), and found that it had a totally different look and feel to it which isn't reflected on your Chronicling America site, and appears to be unfinished in a few areas.  It was using the bootstrap UI, and seems like it could be a good starting point next time we rebuild our theme, but I'm not sure how much of it is functional.  Needless to say, it's so different from what we're working with that I doubt any changes on the Oregon Newspaper side would make sense there.

Given these issues, it's hard to know how best to proceed so our codebases don't diverge so much that we end up with two totally distinct projects.  We're talking about working on a state-based theme sometime next year, but in the meantime (or if we don't have time for that), what is the "right" way to set up a fork for contributing changes?  Should we contribute changes to loc/ ?  Or should we just ignore the HTML entirely and only try to contribute changes to core, non-template files?

**Comment by johnscancella** [comment]
Hi @jechols If we want to contribute to the chronam repository I would create a fork and submit pull requests ( a good overview can be found [here](https://gist.github.com/Chaser324/ce0505fbed06b947d962))

The LoC theme is installed separately and is not publicly available. However the django documentation should get you started https://django-admin2.readthedocs.io/en/latest/ref/themes.html
