### ISSUE TITLE
Centralize image URLs

### ISSUE THREAD

**Issue by jechols** [LibraryOfCongress/chronam#109]
When setting up our fork of chronam for use with our external image server, we found that the app had a great deal of different ways to point to a URL that resolved by generating an image.  Because of this, we weren't able to run exclusively with JP2s without some work.  You can see the branch where we did this work here: https://github.com/uoregon-libraries/oregonnews/commit/c8aad3287bf80cc4ca6716b91abd8b714be956a1

We want to start "un-customizing" our code, and if you're interested I'll throw together a pull request which centralizes URLs in the core code (and whatever themes are currently in master), but I wanted to make sure our changes would be acceptable.  The biggest changes are that we made only two URLs for image derivatives: `/images/tiles` and `/images/resize`.  The "thumbnails" use the same handler and code path as "medium" images just by specifying a parameter.  All tiles go through the tile handler in the same way, instead of having two distinct tile URLs.

We would of course make sure the changes work with our external image server as well as the built-in TIFF server.

**Comment by acdha** [comment]
#210 added the ability to use a separate IIIF server
