### ISSUE TITLE
links to batches not correct

### ISSUE THREAD

**Issue by johnscancella** [LibraryOfCongress/chronam#120]
When viewing batches by languages the links to specific batches are not correct.
For example, when viewing all the french batches (http://chroniclingamerica.loc.gov/languages/fre/batches/) batch batch_lu_franklin_ver02 incorrectly links to http://chroniclingamerica.loc.gov/languages/fre/batch_lu_franklin_ver02/ instead of the correct http://chroniclingamerica.loc.gov/batches/batch_lu_franklin_ver02/

**Comment by tongwang** [comment]
Correction: The link (such as http://chroniclingamerica.loc.gov/languages/fre/batch_lu_franklin_ver02/) is correct.  There is a defect in template `language_batch_pages.html` that causes the error.

**Comment by myusuf** [comment]
Issue is resolved
