### ISSUE TITLE
Add New 2015 Awardees

### ISSUE THREAD

**Issue by nwy** [LibraryOfCongress/chronam#123]
Add two new awardee institutions (and corresponding marc org codes) to the awardee table on both QR and production instances of chronam:
http://chroniclingamerica.loc.gov/awardees/

University of Delaware Library, Newark, DE (deu)
Wisconsin Historical Society (whi)

**Comment by myusuf** [comment]
Updated in QR
http://ndnpqr01vlp.loc.gov/awardees/

**Comment by myusuf** [comment]
New Awardees are added in production:
http://chroniclingamerica.loc.gov/awardees/

**Comment by sasidharpa** [comment]
Hi,

The link is not working http://chroniclingamerica.loc.gov/awardees/, please share 

Regards,
Sasidhar P
