### ISSUE TITLE
Migrate chronicling america to HTTPS

### ISSUE THREAD

**Issue by myusuf** [LibraryOfCongress/chronam#125]
-Changes in server configurations
-Updating application's  internal hard coded links to https

**Comment by mattjensen** [comment]
I want to add my two cents and give my use case, my reason why I would like the site to more fully support HTTPS.  I'm writing some tools that support user accounts (preferences, query history, etc), so I need HTTPS support for my site. It's problematic to try to have my site's client-side JavaScript pull down files (OCR text, in particular) that are not served under HTTPS. Thanks!
