### ISSUE TITLE
ChromAm Referrer Links / Campaign Codes broken

### ISSUE THREAD

**Issue by nwy** [LibraryOfCongress/chronam#126]
Tracking of campaign codes set up by Communications is not working.  The ? to # transformation is still happening in some ChronAm URLs. We can’t track the social channels that are leading to ChronAm via our campaign code process when this URL change occurs.

From email chain...

... the chronam back end (server side) that’s changing the url by redirecting it to the url with the hash.  The request is clearly for the url with the query string:
Request URL: http://chroniclingamerica.loc.gov/lccn/sn85066387/1898-01-16/ed-1/seq-23/?loclr=blogloc
Request Method: GET
Status code: 302
Here are the relevant response headers, the culprit indicated by the ‘Location’ header and 302 status (telling the browser to ‘go here instead’):
…
Location: http://chroniclingamerica.loc.gov/lccn/sn85066387/1898-01-16/ed-1/seq-23/#loclr=blogloc
Server: Apache/2.2.15 (Red Hat)
Vary: Referer,Accept-Encoding
Via: 1.1 varnish
x-varnish: 1618434448 1617911573
Its likely a small over sight in the ui that tries to store application state in the location hash (common paradigm for javascript rich ui components that want to be bookmarkable but not send a request/response). It doesn’t account for parameters outside its application domain needing to be preserved as query parameters.

**Comment by johnscancella** [comment]
to see the varnish replies
curl -sSLIXGET "http://chroniclingamerica.loc.gov/lccn/sn85066387/1898-01-16/ed-1/seq-23/?loclr=blogloc"
