### ISSUE TITLE
Unload Batch

### ISSUE THREAD

**Issue by delacruzmay** [LibraryOfCongress/chronam#128]
newbie here sorry for my question, i just want to ask if there's a way to unload batches previously loaded in ChronAm?

**Comment by myusuf** [comment]
@delacruzmay, there is a management command called batch_purge that you can use for this purpose:
https://github.com/LibraryOfCongress/chronam/blob/master/core/management/commands/purge_batch.py

**Comment by delacruzmay** [comment]
thanks for your reply @myusuf. Unfortunately, when i tried the purge_batch.py, it gives an error only. :(

**Comment by delacruzmay** [comment]
@myusuf - i got the correct command and it was purged. thanks a lot

**Comment by myusuf** [comment]
great!
