### ISSUE TITLE
Local Server and LoC Chronam Awardee Synchronization

### ISSUE THREAD

**Issue by delacruzmay** [LibraryOfCongress/chronam#135]
Hi, I just want to ask, we have a local chronam server that we are using for Quality Assurance process. 

Is there a way that we can download the LoC ChronAm awardee or list of institution database to synchronize it with what we have on our local?

thank you,
May

**Comment by myusuf** [comment]
@delacruzmay, the awardee data is included in the initail data fixture: https://github.com/LibraryOfCongress/chronam/blob/master/core/fixtures/initial_data.json
you can load it by running **django-admin loaddata initial_data**
