### ISSUE TITLE
Add Norwegian Bokmål to Language fixture

### ISSUE THREAD

**Issue by nwy** [LibraryOfCongress/chronam#145]
Add Norwegian Bokmål (nob) to https://github.com/LibraryOfCongress/chronam/blob/9bd101f87afffa2c7ffea9e5209e3fd4d919ccdb/core/fixtures/languages.json

On QR VM and production

**Comment by nwy** [comment]
If this is applicable here, the language display name (in drop down menu) should just say "Norwegian".

**Comment by myusuf** [comment]
So how do you want to  differentiate `nor` and `nob` since they will both show as `Norwegian`?
should it be `Norwegian(Bokmål)`?

**Comment by nwy** [comment]
For now we only need to be concerned with nob.
