### ISSUE TITLE
Increase max length of section_label

### ISSUE THREAD

**Issue by nwy** [LibraryOfCongress/chronam#146]
Batches batch_idhi_doyle_ver01 and batch_deu_horcrux_ver01 are failing to ingest due to the database limit of 100 characters for the section_label. We should update it to 150.

**Comment by johnscancella** [comment]
so just upping it to 150 won't entirely solve the problem. Looking at the XSD (which defines what you can put in the field) http://www.loc.gov/standards/mods/v3/mods-3-0.xsd it does not specify what the max length can be. Be default, XSD will allow unlimited length, so there is nothing to stop someone from using a string length of 151 and breaking it again.

Perhaps we should think about having a extra validation in the DVV to catch these things earlier?

**Comment by nwy** [comment]
Agreed.  The extra check in the DVV would be helpful for data going into LC systems, but we should keep in mind that DVV users might use the DVV to validate content destined for other systems, too.  Maybe a notify type of error can be reported instead of a validation failure?  I can open a DVV ticket to discuss this.

**Comment by johnscancella** [comment]
The ingest completed correctly now that the database has been updated
