### ISSUE TITLE
Update usage of logging in management commands

### ISSUE THREAD

**Issue by acdha** [LibraryOfCongress/chronam#179]
We currently have a number of management commands which report important details only in a log file - e.g. if you run `django-admin purge_batch` it will fail with a generic message. 

I would propose bringing this closer to standard Django practice where the management commands themselves would write to self.stdout / self.stderr so the user always sees the output and logging is reserved for the core code which is usually running in a server context.

**Comment by johnscancella** [comment]
Does celery capture this stdout/stderr? If not, how do we keep the output when running the same commands using celery?
