### ISSUE TITLE
chronam user guide

### ISSUE THREAD

**Issue by savuth-ddd** [LibraryOfCongress/chronam#200]

**Comment by savuth-ddd** [comment]
Hi,
I am new to chronam tool, anyone please help me to share user guide related to tool.
Thanks,

**Comment by jscancella** [comment]
Hi @savuth-ddd, This software project is no longer being actively developed at the Library of Congress. Consider using the Open-ONI (https://github.com/open-oni) fork of the chronam software. Project mailing list: http://listserv.loc.gov/archives/chronam-users.html.
