### ISSUE TITLE
Actively developed?

### ISSUE THREAD

**Issue by epicfaace** [LibraryOfCongress/chronam#204]
It says "This software project is no longer being actively developed at the Library of Congress." However, looks like people like @acdha have been recently committing to this project. So, is this project actually in active maintenance?

I'm trying to see whether it would be better for our organization to start using chronam or open-oni.

**Comment by acdha** [comment]
I would recommend contributing to open-oni. My work on this is currently limited just to what we need to maintain our running system until its replacement is ready. If you see some of the optimizations or bug fixes I've been making which might be of interest for open-oni, they should be relatively easy to pull over but I haven't taken the time to reconcile our repository with the open-oni fork.
