### ISSUE TITLE
Update Adobe tracking script

### ISSUE THREAD

**Issue by nwy** [LibraryOfCongress/chronam#271]
The Adobe tracking script on chroniclingamerica.loc.gov needs to be updated. Here are the implementation instructions:
 
Remove the following at the closing of the </body>:
 
<script src="https://cdn.loc.gov/js/global/metrics/sc/s_code.js" charset="utf-8"></script>
 
Paste this code inside the <head> tag.
 
                <script src="https://assets.adobedtm.com/f94f5647937d/624e2240e90d/launch-0610ec681aff.min.js" async></script>

**Comment by acdha** [comment]
Closed in 34b3632545f1c81c20002c96971b9761d0fc343e
