### ISSUE TITLE
urlopen function fails, wants file:/ in front of file paths

### ISSUE THREAD

**Issue by dbrunton** [LibraryOfCongress/chronam#72]
I've seen it twice- once in the native imaging aware_cext, and once in ChronAm proper.  What's the right way to deal with this- pin to a previous version? Correct the code to this version?

**Comment by johnscancella** [comment]
Does this still happen? I feel like it has been overcome by events

**Comment by acdha** [comment]
I'm closing this in the absence of a way to reproduce it
