### ISSUE TITLE
OCR Dump - Remove partially generated files, requeue

### ISSUE THREAD

**Issue by dbrunton** [LibraryOfCongress/chronam#83]
Looks like the OCR dump left a few files in an inconsistent state: the file generated, but not present in the list (see for example, batch batch_vtu_danby_ver01 in the current public site). When we requeue the dump_ocr command, we should make sure it picks up any that didn't complete, and if it does fail for some reason, it would be nice if it picked up after itself.

**Comment by johnscancella** [comment]
OBE?

**Comment by johnscancella** [comment]
@nwy says yes, so closing
