### ISSUE TITLE
A-Z sort by Title on "All Digitized Newspapers List" limited by specific states 

### ISSUE THREAD

**Issue by nwy** [LibraryOfCongress/chronam#88]
It appears that when viewing all digitized titles list limited to a specific state, the list is sorted A-Z except for the last few titles.  In these examples, the out of order titles are from recently ingested batches. 

http://chroniclingamerica.loc.gov/newspapers/?state=Tennessee&ethnicity=&language=

http://chroniclingamerica.loc.gov/newspapers/?state=Washington&ethnicity=&language

The entire list (all states) seems ok:
http://chroniclingamerica.loc.gov/newspapers/

**Comment by dbrunton** [comment]
The sort is currently sorting with uppercase first, and lowercase second. Should be case insensitive.
