### ISSUE TITLE
chronam_sync dependent on access to ndnp-essays.rdc.lctl.gov

### ISSUE THREAD

**Issue by edsu** [LibraryOfCongress/chronam#9]
The chronam_sync management command will not work outside of the Library of Congress since it expects to be able to grab an Atom feed from ndnp-essays.rdc.lctl.gov, which is not publicly available. We have (at least) a few options for fixing this:
- change the management command to not poll for essays by default
- periodically make the essays part of the chronam repository (they aren't big) for loading locally
- have chroniclingamerica.loc.gov make a feed of the essays available as well
- make the essay editor publicly available at ndnp-essays.rdc.lctl.gov, or another awardee institution

Thoughts?

**Comment by johnscancella** [comment]
indeed the `--skip-essays` option should fix this. @davidhart0 if you are still having problems loading please open a new issue. Thanks!
