### ISSUE TITLE
Piedmont (Italy) displayed as US state

### ISSUE THREAD

**Issue by nwy** [LibraryOfCongress/chronam#93]
This title - http://chroniclingamerica.loc.gov/lccn/2012271201/ - is showing up as belonging to the state of Piedmont in Chronicling America.  This is because one of its Geographic Coverage areas is in Piedmont region of Italy.  (Paper was published in multiple places during its life.  Chronam is drawing from one of the 752$b fields as expected). 

Not sure what the exact action is here, but we should only populate our list of state and state drop-downs with US states and territoties.

**Comment by prbl** [comment]
Piedmont still shows as state for this title in https://chroniclingamerica.loc.gov/newspapers.json

**Comment by nwy** [comment]
“Due to US newspaper cataloging conventions and Chronicling America’s use of the standardized MARC fields for populating the location drop downs, Piedmont is displaying in the “State” drop down and in the various locations mentioned.  Please note that, with the exception of maintenance related work, this software project is no longer being actively developed at the Library of Congress. Work is underway to move the Chronicling America newspapers collection into The Library of Congress digital collections environment.  Consider using the Open-ONI (https://github.com/open-oni) fork of the chronam software. Project mailing list: http://listserv.loc.gov/archives/chronam-users.html.  “
