### ISSUE TITLE
County searches in Directory return counties with same name in other states

### ISSUE THREAD

**Issue by nwy** [LibraryOfCongress/chronam#94]
When you search for papers in a specifc state and county, the search results include titles also published in counties in other states that have the same county name.  For instance, a search limiting to North Carolina and Franklin County returns papers in Franklin County, NC, but also the title Fuller's gleaner (http://chroniclingamerica.loc.gov/lccn/sn91068045/), which  is in Buncombe County.
 I think it has to do with the fact that Franklin, New York, is included in its geographic coverage.  Perhaps when state and county are both used as search criteria, the results should only include titles that have the exact state and county within the same 752 field?

http://chroniclingamerica.loc.gov/search/titles/results/?state=North+Carolina&county=Franklin&city=&year1=1690&year2=2014&terms=&frequency=&language=&ethnicity=&labor=&material_type=&lccn=&rows=20

**Comment by johnscancella** [comment]
@nwy is this still a problem?
