### ISSUE TITLE
Page Search

### ISSUE THREAD

**Issue by cjehr** [LibraryOfCongress/chronam#97]
The ability to search the text of only the page (or maybe issue) that the user is currently viewing would be nice.

**Comment by johnscancella** [comment]
you can search on the PDF or Text view
For example for the page http://chroniclingamerica.loc.gov/lccn/sn85042243/1917-07-19/ed-1/seq-1/
you can do the pdf view http://chroniclingamerica.loc.gov/lccn/sn85042243/1917-07-19/ed-1/seq-1.pdf
or the text view http://chroniclingamerica.loc.gov/lccn/sn85042243/1917-07-19/ed-1/seq-1/ocr/
which both use the default search in the web browser.
